"""Generate the runtime registry of fireable jobs from service manifests."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat

from framework.generators.base import BaseGenerator


class JobsManifestGenerator(BaseGenerator):
    """Render the loader's deterministic product job registry."""

    def generate(self) -> list[Path]:
        schemas = self.specs.job_schemas
        sources = self.specs.job_schema_sources
        providers: dict[str, list[str]] = {}
        for service_name, manifest in sorted(self.specs.manifests.items()):
            for capability in sorted(manifest.provides):
                providers.setdefault(capability, []).append(service_name)

        for service_dir in sorted((self.repo_root / "services").glob("*/")):
            if service_dir.name != "backend":
                continue
            output_file = service_dir / "src" / "generated" / "jobs_schemas.py"
            self.write_file(output_file, self._render_content(schemas, sources, providers))
            self.format_file(output_file)
            return [output_file]
        return []

    @staticmethod
    def _render_content(
        schemas: dict[str, object],
        sources: dict[str, str],
        providers: dict[str, list[str]],
    ) -> str:
        schemas_value = pformat(schemas, sort_dicts=True, width=88)
        sources_value = pformat(sources, sort_dicts=True, width=88)
        providers_value = pformat(providers, sort_dicts=True, width=88)
        return (
            "# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT\n"
            '"""Fireable job declarations collected from service manifests.\n\n'
            "JOB_SCHEMAS is the fail-closed allow-list of names the core jobs contract\n"
            "may fire, mapped to the JSON Schema each fire's arguments must satisfy.\n"
            "JOB_CAPABILITY_PROVIDERS records which services declared that they provide a\n"
            "core capability. It is descriptive only: the core never resolves a provider,\n"
            'it emits the declared event and a subscriber does the work.\n"""\n\n'
            "from __future__ import annotations\n\n"
            f"JOB_SCHEMAS: dict[str, object] = {schemas_value}\n\n"
            f"JOB_SCHEMA_SOURCES: dict[str, str] = {sources_value}\n\n"
            f"JOB_CAPABILITY_PROVIDERS: dict[str, list[str]] = {providers_value}\n"
        )
