"""Generate the runtime identity of the build-time active package set."""

from __future__ import annotations

import json
from pathlib import Path

from framework.generators.base import BaseGenerator


class PackageContractGenerator(BaseGenerator):
    """Pin runtime activation to the exact package set used for generation."""

    def generate(self) -> list[Path]:
        output = self.repo_root / "codegen_kit" / "_active_packages.py"
        identities = [
            {
                "manifest_sha256": package.manifest_sha256,
                "name": package.name,
                "version": package.manifest.version,
            }
            for package in self.specs.packages
        ]
        content = (
            "# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT\n"
            '"""Package identities used to generate this product contract."""\n\n'
            f"ACTIVE_PACKAGES: list[dict[str, str]] = "
            f"{json.dumps(identities, indent=4, sort_keys=True)}\n"
        )
        self.write_file(output, content)
        self.format_file(output)
        return [output]
