"""Generate the runtime registry from explicit service settings manifests."""

from __future__ import annotations

import json
from pathlib import Path

from framework.generators.base import BaseGenerator


class SettingsManifestGenerator(BaseGenerator):
    """Emit one deterministic, backend-consumable settings schema registry."""

    def generate(self) -> list[Path]:
        schemas: dict[str, object] = {}
        sources: dict[str, str] = {}
        for service_name, manifest in sorted(self.specs.manifests.items()):
            properties = manifest.settings_schema["properties"]
            for key, schema in sorted(properties.items()):
                if key in schemas:
                    msg = (
                        f"Setting '{key}' is declared by both '{sources[key]}' and '{service_name}'"
                    )
                    raise ValueError(msg)
                schemas[key] = schema
                sources[key] = service_name
        for package in self.specs.packages:
            source = f"package:{package.name}"
            prefix = package.name.replace("-", "_")
            for local_name, schema in sorted(
                package.manifest.settings_schema["properties"].items()
            ):
                key = f"{prefix}.{local_name}"
                if key in schemas:
                    raise ValueError(
                        f"Setting '{key}' is declared by both '{sources[key]}' and '{source}'"
                    )
                schemas[key] = schema
                sources[key] = source

        for service_dir in sorted((self.repo_root / "services").glob("*/")):
            if service_dir.name != "backend":
                continue
            output_file = service_dir / "src" / "generated" / "settings_schemas.py"
            content = self._render_content(schemas, sources)
            self.write_file(output_file, content)
            self.format_file(output_file)
            return [output_file]
        return []

    @staticmethod
    def _render_content(schemas: dict[str, object], sources: dict[str, str]) -> str:
        rendered_schemas = json.dumps(schemas, indent=4, sort_keys=True)
        rendered_sources = json.dumps(sources, indent=4, sort_keys=True)
        import_line = "import json\n\n" if schemas or sources else ""
        schemas_value = (
            f"json.loads(\n    r'''{rendered_schemas}'''\n)" if schemas else "{}"
        )
        sources_value = (
            f"json.loads(\n    r'''{rendered_sources}'''\n)" if sources else "{}"
        )
        return (
            "# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT\n"
            '"""Validated settings schemas declared by service manifests."""\n\n'
            "from __future__ import annotations\n\n"
            f"{import_line}"
            f"SETTINGS_SCHEMAS: dict[str, object] = {schemas_value}\n\n"
            f"SETTINGS_SCHEMA_SOURCES: dict[str, str] = {sources_value}\n"
        )
