"""Generate the runtime registry from explicit service settings manifests."""

from __future__ import annotations

import json
from pathlib import Path

from framework.generators.base import BaseGenerator


class SettingsManifestGenerator(BaseGenerator):
    """Render the loader's deterministic product settings registry."""

    def generate(self) -> list[Path]:
        schemas = self.specs.settings_schemas
        sources = self.specs.settings_schema_sources

        for service_dir in sorted((self.repo_root / "services").glob("*/")):
            if service_dir.name != "backend":
                continue
            output_file = service_dir / "src" / "generated" / "settings_schemas.py"
            content = self._render_content(schemas, sources)
            self.write_file(output_file, content)
            self.format_file(output_file)
            return [output_file]
        return []

    @staticmethod
    def _render_content(schemas: dict[str, object], sources: dict[str, str]) -> str:
        rendered_schemas = json.dumps(schemas, indent=4, sort_keys=True)
        rendered_sources = json.dumps(sources, indent=4, sort_keys=True)
        import_line = "import json\n\n" if schemas or sources else ""
        schemas_value = (
            f"json.loads(\n    r'''{rendered_schemas}'''\n)" if schemas else "{}"
        )
        sources_value = (
            f"json.loads(\n    r'''{rendered_sources}'''\n)" if sources else "{}"
        )
        return (
            "# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT\n"
            '"""Validated settings schemas declared by service manifests."""\n\n'
            "from __future__ import annotations\n\n"
            f"{import_line}"
            f"SETTINGS_SCHEMAS: dict[str, object] = {schemas_value}\n\n"
            f"SETTINGS_SCHEMA_SOURCES: dict[str, str] = {sources_value}\n"
        )
