"""Generate the runtime registry from explicit service settings manifests."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat

from framework.generators.base import BaseGenerator


class SettingsManifestGenerator(BaseGenerator):
    """Render the loader's deterministic product settings registry."""

    def generate(self) -> list[Path]:
        schemas = self.specs.settings_schemas
        sources = self.specs.settings_schema_sources
        scopes = self.specs.settings_schema_scopes

        for service_dir in sorted((self.repo_root / "services").glob("*/")):
            if service_dir.name != "backend":
                continue
            output_file = service_dir / "src" / "generated" / "settings_schemas.py"
            content = self._render_content(schemas, sources, scopes)
            self.write_file(output_file, content)
            self.format_file(output_file)
            return [output_file]
        return []

    @staticmethod
    def _render_content(
        schemas: dict[str, object], sources: dict[str, str], scopes: dict[str, str]
    ) -> str:
        schemas_value = pformat(schemas, sort_dicts=True, width=88)
        sources_value = pformat(sources, sort_dicts=True, width=88)
        scopes_value = pformat(scopes, sort_dicts=True, width=88)
        return (
            "# AUTO-GENERATED BY SERVICE-TEMPLATE - DO NOT EDIT\n"
            '"""Validated settings schemas declared by service manifests."""\n\n'
            "from __future__ import annotations\n\n"
            f"SETTINGS_SCHEMAS: dict[str, object] = {schemas_value}\n\n"
            f"SETTINGS_SCHEMA_SOURCES: dict[str, str] = {sources_value}\n\n"
            "# The only scope a core-owned setting may be read or written in.\n"
            f"SETTINGS_SCHEMA_SCOPES: dict[str, str] = {scopes_value}\n"
        )
